# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae6adbe5829299e630aaf2ba41353d5aa2aa3abed06a70a4874beb25544e2b95c97d248308affa48c992a1123d16d0e20a1bd18ceccccf5818837c69afe76531

test:
  secret_key_base: 91430bfdba3b7ae3dc05a672fcac9fac942dd9bcf40369335e057ae9518d034550bb4af84158769323f294aa117cc8282401579127c5ce051ae8c4a6aec74bc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
